services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: authentication-api

    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - .env

    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

    volumes:
      - .:/app
      - /app/node_modules

    networks:
      - authentication-network


  mongo:
    image: mongo:8

    container_name: authentication-mongo

    restart: unless-stopped

    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_DATABASE: authentication_db

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "db.adminCommand('ping').ok"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - authentication-network


  redis:
    image: redis:8-alpine

    container_name: authentication-redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - authentication-network


volumes:
  mongo_data:
  redis_data:


networks:
  authentication-network:
    driver: bridge